type codeType = {
  [key: string]: string;
};

export const ERROR_CODE: codeType = {
  "-46": "Tài khoản đã tồn tại !",
  "-7": "OTP không chính xác !",
  "-13": "Thẻ đã hết ! Vui lòng chọn thẻ khác hoặc thử lại sau.",
  "-41": "Email đã được đăng ký.",
  "-42": "Thông tin Email truyền vào không hợp lệ !",
  "-48": "Tài khoản đã bị khóa !",
  "-49": "Tài khoản chưa được kích hoạt !",
  "-50": "Tài khoản không tồn tại !",
  "-51": "Tài khoản không đủ số dư !",
  "-99": "Lỗi hệ thống !",
  "-641": "Số điện thoại đã được đăng ký.",
  "-97": "Không gửi được OTP (lỗi gửi sms) !",
  "-642": "Số điện thoại không đúng !",
  "-644": "Số lần gửi OTP vượt quá số lượng cho phép (tối đa 3 lần/ngày) !",
  "-645": "Thời gian 2 lần gửi OTP quá ngắn !",
  "-600": "Dữ liệu đầu vào không đúng !",
  "-663": "Lỗi đổi mật khẩu (mật khẩu mới giống mật khẩu cũ) !",
  "-613": "Mật khẩu cũ không chính xác  !",
  "-10000": "Chưa đăng nhập !",
  "-10001": "Thông tin truyền vào không hợp lệ !",
  "-10002": "Số điện thoại không hợp lệ.",
  "-10003": "Thông tin password truyền vào không hợp lệ !",
  "-10004": "Thông tin fullname truyền vào không hợp lệ !",
  "-10005": "Thông tin OTP truyền vào không hợp lệ!	",
  "-10006": "Thông tin đã hết hiệu lực !",
  "-10007": "Thông tin Token không hợp lệ !",
  "-10008": "Captcha không chính xác.",
  "-10009": "Mật khẩu cũ không hợp lệ !",
  "-10010": "Mật khẩu mới không hợp lệ !",
  "-10011": "Tài khoản đã xác thực !",
  "-10012": "Tài khoản đã xác thực !",
  "-10013": "Tài khoản chưa cập nhật email !",
  "-10015": "Tài khoản đã được kích hoạt !",
};
